export interface RoleCategory {
  id: string;
  name: string;
  emoji: string;
  label: string;
  tagline: string;
  description: string;
  badge: string;
  featuredToolIds: string[];
  roleSpecificOverrides?: Record<
    string,
    { title: string; subtitle: string; badge?: string }
  >;
  allToolIds: string[];
}

export const ROLES: RoleCategory[] = [
  {
    id: 'student',
    name: 'Student',
    emoji: '🎓',
    label: '🎓 Student',
    tagline: 'Homework, notes, exam form compression & study guides',
    description: 'Designed for students: scan notebooks, compress for exam portals under 200KB, merge lectures, and convert to Word.',
    badge: 'Exam & Notes Ready',
    featuredToolIds: ['scan-to-pdf', 'compress-pdf', 'merge-pdf', 'pdf-to-word'],
    roleSpecificOverrides: {
      'scan-to-pdf': {
        title: 'Camera Scanner',
        subtitle: 'Scan handwritten notebook pages and assignments directly with phone or laptop camera.',
        badge: 'Instant Scan',
      },
      'compress-pdf': {
        title: 'Compress under 200KB',
        subtitle: 'Shrink exam application forms, marksheets, and resumes to strict upload limits.',
        badge: 'Strict <200KB',
      },
      'merge-pdf': {
        title: 'Merge Notes & Slides',
        subtitle: 'Combine lecture slides, teacher handouts, and study chapters into one clean PDF.',
        badge: 'Top Pick',
      },
      'pdf-to-word': {
        title: 'PDF to Word',
        subtitle: 'Convert lecture notes and question banks to editable Microsoft Word documents.',
        badge: 'Editable',
      },
      'listen-pdf': {
        title: 'Audio PDF Reader',
        subtitle: 'Listen to textbooks, notes, and study guides with natural Hindi & English speech synthesis.',
        badge: 'Audio Study',
      },
      'booklet-formatter': {
        title: 'Booklet Print Formatter',
        subtitle: 'Print 2-up or 4-up notes on single sheets with cut-lines to save 50%-75% paper.',
        badge: 'Paper Saver',
      },
      'govt-form-resizer': {
        title: 'Govt Exam Photo & Sig Resizer',
        subtitle: 'Auto-compress passport photos & signatures to strict KB limits for SSC, UPSC, NTA.',
        badge: '100% Valid',
      },
      'bookmark-generator': {
        title: 'Bookmark & TOC Generator',
        subtitle: 'Generate clickable chapters and table of contents outlines for textbooks and study notes.',
        badge: 'TOC Outlines',
      },
      'form-filler': {
        title: 'Form Field Filler',
        subtitle: 'Fill exam application forms, scholarship PDFs, and admission paperwork directly in browser.',
        badge: 'Fill & Sign',
      },
      'ink-saver': {
        title: 'Ink Saver & Toner Eco Mode',
        subtitle: 'Strip dark background fills and colored slide backgrounds to save up to 70% printer ink.',
        badge: 'Save 70% Ink',
      },
      'vernacular-ocr': {
        title: 'Hindi & English OCR to Word',
        subtitle: 'Extract notes, assignments, and Hindi/English exam papers to editable Word documents.',
        badge: 'Hindi OCR',
      },
      'perspective-cropper': {
        title: 'Perspective Photo Cropper & Flattener',
        subtitle: 'Fix tilted camera photos of notebook pages, book chapters, and identity proofs into flat sheets.',
        badge: 'Photo Flattener',
      },
      'merge-numbering': {
        title: 'Batch Merge with Running Page Numbers',
        subtitle: 'Combine multiple chapters and study handouts with continuous pagination (Page X of Total).',
        badge: 'Numbered Notes',
      },
    },
    allToolIds: [
      'scan-to-pdf',
      'compress-pdf',
      'merge-pdf',
      'pdf-to-word',
      'listen-pdf',
      'booklet-formatter',
      'govt-form-resizer',
      'bookmark-generator',
      'form-filler',
      'ink-saver',
      'vernacular-ocr',
      'perspective-cropper',
      'merge-numbering',
      'word-to-pdf',
      'ocr-pdf',
      'pdf-to-text',
      'organize-pdf',
      'rotate-pages',
      'remove-pages',
    ],
  },
  {
    id: 'teacher',
    name: 'Teacher',
    emoji: '👨‍🏫',
    label: '👨‍🏫 Teacher',
    tagline: 'Exam papers, question banks, page splitting & watermarking',
    description: 'Built for educators: correct typos in question papers, watermark confidential tests, split pages, and assemble question banks.',
    badge: 'Educator Suite',
    featuredToolIds: ['pdf-editor', 'add-watermark', 'split-pdf', 'merge-pdf'],
    roleSpecificOverrides: {
      'pdf-editor': {
        title: 'Direct Text Edit',
        subtitle: 'Fix typos, update marks, and edit exam questions directly without rewriting files.',
        badge: 'Direct Edit',
      },
      'add-watermark': {
        title: 'Watermark Exam Papers',
        subtitle: 'Stamp "CONFIDENTIAL", school name, or custom watermark on question papers.',
        badge: 'Security',
      },
      'split-pdf': {
        title: 'Split Pages & Chapters',
        subtitle: 'Separate question sections, extract homework assignments, and distribute specific tests.',
        badge: 'Quick Split',
      },
      'merge-pdf': {
        title: 'Merge Question Bank',
        subtitle: 'Compile yearly question banks, syllabus guides, and answer keys in proper order.',
        badge: 'Essential',
      },
      'booklet-formatter': {
        title: 'Exam Booklet Formatter',
        subtitle: 'Arrange question papers, test booklets, and answer keys in 2-up A4 printable format with cut-marks.',
        badge: 'Exam Print',
      },
      'listen-pdf': {
        title: 'Audio Proof Reader',
        subtitle: 'Listen to question papers and handouts aloud to catch typos and phrasing errors effortlessly.',
        badge: 'Voice Proof',
      },
      'bookmark-generator': {
        title: 'Syllabus & TOC Generator',
        subtitle: 'Create clickable index chapters and navigation outlines for textbooks and question compilations.',
        badge: 'TOC Outlines',
      },
    },
    allToolIds: [
      'pdf-editor',
      'add-watermark',
      'split-pdf',
      'merge-pdf',
      'booklet-formatter',
      'listen-pdf',
      'bookmark-generator',
      'page-numbers',
      'header-footer',
      'crop-pdf',
      'redact-pdf',
      'scan-to-pdf',
      'pdf-to-word',
    ],
  },
  {
    id: 'creator',
    name: 'Creator & Studio',
    emoji: '🎨',
    label: '🎨 Creator & Studio',
    tagline: 'Photo proofing, album PDF, WhatsApp shrink & watermark',
    description: 'Tailored for photographers, designers & creators: proof albums with star ratings, make photobooks, and share via WhatsApp.',
    badge: 'Studio Pro',
    featuredToolIds: ['photo-proofing', 'image-to-pdf', 'compress-pdf', 'add-watermark'],
    roleSpecificOverrides: {
      'photo-proofing': {
        title: 'Photo Proofing & Selection',
        subtitle: 'Let clients rate 1-5★, heart favorites, reject shots, and export Lightroom filenames & contact sheets.',
        badge: 'Client Favorite',
      },
      'image-to-pdf': {
        title: 'Image to PDF Album',
        subtitle: 'Combine high-res JPG/PNG photoshoot images into a bound, high-definition photobook PDF.',
        badge: 'Lossless',
      },
      'compress-pdf': {
        title: 'WhatsApp Compressor',
        subtitle: 'Shrink wedding preview albums under 15MB for effortless delivery on WhatsApp & mobile.',
        badge: 'Mobile Ready',
      },
      'add-watermark': {
        title: 'Watermark Stamping',
        subtitle: 'Batch stamp studio logos or copyright stamps to protect unreleased client photo proofs.',
        badge: 'Copyright',
      },
      'carousel-maker': {
        title: 'Social Media Carousel Maker',
        subtitle: 'Convert PDF slides and notes into 1080x1350 vertical or 1080x1080 square Instagram/LinkedIn carousel images with 1-click ZIP export.',
        badge: 'Viral Format',
      },
      'batch-renamer': {
        title: 'Batch Renamer & EXIF Wiper',
        subtitle: 'Bulk rename 50+ event albums and client preview PDFs with sequential numbering and strip camera metadata.',
        badge: 'Bulk Studio',
      },
      'n-up-imposition': {
        title: 'N-Up Grid Imposition for Print',
        subtitle: 'Impose 2-up, 4-up, and 9-up layouts on A4/A3 sheets with cutting guidelines for cards and prints.',
        badge: 'Print Shop',
      },
    },
    allToolIds: [
      'wedding-studio',
      'photo-proofing',
      'carousel-maker',
      'batch-renamer',
      'n-up-imposition',
      'image-to-pdf',
      'compress-pdf',
      'add-watermark',
      'wedding-quotation',
      'guest-cards',
      'pdf-to-images',
      'resize-pdf',
    ],
  },
  {
    id: 'business',
    name: 'Business & Cyber Cafe',
    emoji: '💼',
    label: '💼 Business & Cyber Cafe',
    tagline: 'ID card print layout, invoices, receipts & digital signing',
    description: 'Designed for cyber cafe owners, shops & retail: 4-in-1/8-in-1 Aadhaar/PAN print layout, instant quotations, and e-signatures.',
    badge: 'Retail Ready',
    featuredToolIds: ['id-card-layout', 'wedding-quotation', 'sign-pdf', 'scan-to-pdf'],
    roleSpecificOverrides: {
      'id-card-layout': {
        title: 'ID Card 4-in-1/8-in-1 Print Layout',
        subtitle: 'Print Aadhaar, PAN, and Voter IDs front & back with exact CR80 sizing and scissor cut marks.',
        badge: 'Cyber Cafe Pro',
      },
      'wedding-quotation': {
        title: 'Invoice / Quotation Maker',
        subtitle: 'Generate professional service quotations, automated GST taxes, and integrated dual e-signatures.',
        badge: 'Auto GST',
      },
      'sign-pdf': {
        title: 'Digital E-Signature',
        subtitle: 'Sign contracts, application forms, and customer receipts directly in the browser.',
        badge: 'Legal Sign',
      },
      'scan-to-pdf': {
        title: 'Camera Scanner',
        subtitle: 'Quickly scan customer documents, identity cards, and receipts ready for PDF print.',
        badge: 'Fast Print',
      },
      'govt-form-resizer': {
        title: 'Govt Exam Photo & Signature Resizer',
        subtitle: 'Resize customer photos and signatures to exact portal specifications (SSC, UPSC, IBPS, Police, State PSC).',
        badge: 'Cyber Cafe Pro',
      },
      'stamp-qr-overlay': {
        title: 'Custom Stamp & QR Code Inserter',
        subtitle: 'Overlay circular rubber stamps (APPROVED, PAID, VERIFIED) and dynamic payment / verification QR codes onto PDF receipts and certificates.',
        badge: 'Official Seal',
      },
      'form-filler': {
        title: 'Customer Form Filler',
        subtitle: 'Quickly fill scanned government and banking applications with text, checkboxes, and dates.',
        badge: 'Cyber Cafe Pro',
      },
      'ink-saver': {
        title: 'Ink Saver & Toner Eco Mode',
        subtitle: 'Eliminate heavy color backgrounds to save huge printer cartridge and toner costs.',
        badge: 'Save 70% Toner',
      },
      'unlock-permissions': {
        title: 'PDF Permission Unlocker & Decryptor',
        subtitle: 'Remove print locks, copy blocks, and editing restrictions from customer files for instant printing.',
        badge: 'Print Unlocker',
      },
      'n-up-imposition': {
        title: 'Multi-Page N-Up Grid Imposition',
        subtitle: 'Print 2-up, 4-up, or 9-up Aadhaar copies, coupons, and pamphlets with dashed scissor cutting guides.',
        badge: 'Print Shop Pro',
      },
      'perspective-cropper': {
        title: 'Perspective Document Flattener',
        subtitle: 'Flatten slanted smartphone photos of customer ID cards and certificates into scanner-grade sheets.',
        badge: 'Scan Rectifier',
      },
    },
    allToolIds: [
      'id-card-layout',
      'govt-form-resizer',
      'stamp-qr-overlay',
      'booklet-formatter',
      'unlock-permissions',
      'n-up-imposition',
      'perspective-cropper',
      'form-filler',
      'ink-saver',
      'wedding-quotation',
      'sign-pdf',
      'scan-to-pdf',
      'add-watermark',
      'image-to-pdf',
      'resize-pdf',
      'crop-pdf',
      'compress-pdf',
      'repair-pdf',
      'merge-pdf',
    ],
  },
  {
    id: 'office',
    name: 'Office',
    emoji: '🏢',
    label: '🏢 Office',
    tagline: 'Direct text edit, Excel export, password protect & legal Bates',
    description: 'Essential toolkit for office desks, legal teams & administrators: direct PDF text editing, Excel conversions, encryption, and Bates stamps.',
    badge: 'Corporate Grade',
    featuredToolIds: ['pdf-editor', 'pdf-to-excel', 'protect-pdf', 'bates-numbering'],
    roleSpecificOverrides: {
      'pdf-editor': {
        title: 'Direct Text Edit',
        subtitle: 'Edit contract terms, proposals, and official letters directly without converting to Word.',
        badge: 'Direct Edit',
      },
      'pdf-to-excel': {
        title: 'PDF to Excel',
        subtitle: 'Extract financial balances, ledgers, invoice data, and tables cleanly into spreadsheet format.',
        badge: 'Tables & Ledger',
      },
      'protect-pdf': {
        title: 'Password Protect',
        subtitle: 'Encrypt confidential corporate audits, employee records, and payroll PDFs with strong AES passwords.',
        badge: 'Encrypted',
      },
      'bates-numbering': {
        title: 'Bates Numbering',
        subtitle: 'Stamp sequential legal Bates numbers for discovery, compliance, and court document indexing.',
        badge: 'Court Compliant',
      },
      'stamp-qr-overlay': {
        title: 'Official Stamp, Seal & QR Inserter',
        subtitle: 'Stamp official company seals ("APPROVED", "CONFIDENTIAL", "PAID") and dynamic QR codes onto agreements and invoices.',
        badge: 'Company Seal',
      },
      'listen-pdf': {
        title: 'Audio Document Reader',
        subtitle: 'Listen to legal contracts, memos, and long policy documents with background speech synthesis.',
        badge: 'Productivity',
      },
      'pdf-compare': {
        title: 'Side-by-Side PDF Diff & Clause Checker',
        subtitle: 'Inspect contract revisions side-by-side with word/clause addition & deletion highlights.',
        badge: 'Legal Diff',
      },
      'bookmark-generator': {
        title: 'Interactive TOC & Bookmark Outlines',
        subtitle: 'Inject clickable table of contents into corporate reports, policy manuals, and compliance binders.',
        badge: 'Corporate TOC',
      },
      'form-filler': {
        title: 'Form Field Creator & Filler',
        subtitle: 'Fill contracts, tax declarations, and internal requisition forms with baked text & dates.',
        badge: 'Fill & Sign',
      },
      'batch-renamer': {
        title: 'Batch Renamer & Metadata Wiper',
        subtitle: 'Bulk rename corporate documents and wipe confidential author, software, and company metadata.',
        badge: 'Security Wiper',
      },
      'vernacular-ocr': {
        title: 'Regional OCR to Word (.DOCX)',
        subtitle: 'Extract Hindi legal notices, affidavits, and bilingual contracts directly into Microsoft Word.',
        badge: 'Legal OCR',
      },
      'unlock-permissions': {
        title: 'PDF Permission Unlocker & Decryptor',
        subtitle: 'Strip restrictions on printing, content copying, and document assembly from incoming restricted PDFs.',
        badge: 'Security Unlock',
      },
      'merge-numbering': {
        title: 'Batch Merge & Running Numbering',
        subtitle: 'Assemble multi-document court binders, exhibits, and contracts with continuous Bates-style pagination.',
        badge: 'Court Binder',
      },
    },
    allToolIds: [
      'pdf-editor',
      'pdf-to-excel',
      'protect-pdf',
      'bates-numbering',
      'pdf-compare',
      'stamp-qr-overlay',
      'bookmark-generator',
      'form-filler',
      'batch-renamer',
      'vernacular-ocr',
      'unlock-permissions',
      'merge-numbering',
      'listen-pdf',
      'repair-pdf',
      'excel-to-pdf',
      'unlock-pdf',
      'redact-pdf',
      'compare-pdf',
      'metadata',
      'merge-pdf',
      'split-pdf',
    ],
  },
  {
    id: 'all',
    name: 'All Tools',
    emoji: '🌐',
    label: '🌐 All Tools',
    tagline: 'Complete manual catalog of 45+ browser-based tools',
    description: 'Browse the complete unconstrained library of all PDF, document, scanner, and studio tools.',
    badge: '45+ Tools',
    featuredToolIds: ['pdf-editor', 'merge-pdf', 'split-pdf', 'compress-pdf'],
    allToolIds: [], // Empty means all
  },
];
