import { ToolItem } from '../types';

export const TOOLS: ToolItem[] = [
  // Organize
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one unified document in your preferred order.',
    category: 'organize',
    path: '/merge-pdf',
    icon: 'Combine',
    badge: 'Popular',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate pages or extract specific page ranges into standalone PDFs or ZIP.',
    category: 'organize',
    path: '/split-pdf',
    icon: 'Split',
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Sort, reorder, duplicate, delete and insert pages with visual drag & drop.',
    category: 'organize',
    path: '/organize-pdf',
    icon: 'LayoutGrid',
    badge: 'Essential',
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    description: 'Select and permanently delete unwanted pages from your PDF file.',
    category: 'organize',
    path: '/organize-pdf?action=remove',
    icon: 'Trash2',
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Pull out selected pages and generate a new custom PDF document.',
    category: 'organize',
    path: '/split-pdf?mode=extract',
    icon: 'FileUp',
  },
  {
    id: 'rotate-pages',
    name: 'Rotate Pages',
    description: 'Rotate individual or all pages by 90°, 180° or 270° clockwise.',
    category: 'organize',
    path: '/rotate-pdf',
    icon: 'RotateCw',
  },

  // Edit & Sign
  {
    id: 'pdf-editor',
    name: 'PDF Editor',
    description: 'Add text, freehand drawing, annotations, shapes, images and signatures directly.',
    category: 'edit',
    path: '/pdf-editor',
    icon: 'PenTool',
    badge: 'Flagship',
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Draw, type or upload your signature and place it anywhere on document pages.',
    category: 'edit',
    path: '/pdf-editor?tool=signature',
    icon: 'FileSignature',
    badge: 'Popular',
  },
  {
    id: 'add-text',
    name: 'Add Text',
    description: 'Type overlay text anywhere with customizable fonts, sizes, colors and alignments.',
    category: 'edit',
    path: '/pdf-editor?tool=text',
    icon: 'Type',
  },
  {
    id: 'draw-pdf',
    name: 'Draw on PDF',
    description: 'Freehand sketching, markup and highlight with adjustable stroke and opacity.',
    category: 'edit',
    path: '/pdf-editor?tool=draw',
    icon: 'Pencil',
  },
  {
    id: 'highlight-pdf',
    name: 'Highlight PDF',
    description: 'Mark important paragraphs and text passages with translucent color highlighters.',
    category: 'edit',
    path: '/pdf-editor?tool=highlight',
    icon: 'Highlighter',
  },
  {
    id: 'add-shapes',
    name: 'Add Shapes',
    description: 'Insert rectangles, circles, lines and arrows with customized borders and fills.',
    category: 'edit',
    path: '/pdf-editor?tool=shape',
    icon: 'Square',
  },

  // Convert to PDF
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert JPG, PNG, WEBP images into a clean, beautifully formatted PDF.',
    category: 'convert-to',
    path: '/image-to-pdf',
    icon: 'Image',
    badge: 'Popular',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Microsoft Word (.docx) documents into standard PDF files.',
    category: 'convert-to',
    path: '/word-to-pdf',
    icon: 'FileText',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert web code, articles and HTML snippets into clean paginated PDFs.',
    category: 'convert-to',
    path: '/word-to-pdf?mode=html',
    icon: 'Code',
  },

  // Convert from PDF
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    description: 'Export each PDF page as high-resolution JPG or PNG packaged in a ZIP archive.',
    category: 'convert-from',
    path: '/pdf-to-images',
    icon: 'Images',
    badge: 'Popular',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Extract text, formatting and structure into an editable Microsoft Word (.docx).',
    category: 'convert-from',
    path: '/pdf-to-word',
    icon: 'FileDown',
    badge: 'High Demand',
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Extract all readable text from your PDF to copy or download as TXT / Markdown.',
    category: 'convert-from',
    path: '/pdf-to-text',
    icon: 'AlignLeft',
  },

  // Optimize PDF
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size while preserving document visual clarity and image sharpness.',
    category: 'optimize',
    path: '/compress-pdf',
    icon: 'Minimize2',
    badge: 'Popular',
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Fix corrupt, damaged or unreadable PDF files and rebuild document xref tables.',
    category: 'optimize',
    path: '/repair-pdf',
    icon: 'Wrench',
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    description: 'Merge form fields, layers and annotations into one permanent uneditable surface.',
    category: 'optimize',
    path: '/flatten-pdf',
    icon: 'Layers',
  },

  // Page Tools
  {
    id: 'add-watermark',
    name: 'Watermark PDF',
    description: 'Stamp custom text or image watermarks across pages with opacity and angle controls.',
    category: 'page-tools',
    path: '/add-watermark',
    icon: 'Stamp',
    badge: 'Featured',
  },
  {
    id: 'remove-watermark',
    name: 'Remove Watermark',
    description: 'Visual cleanup and redaction workflow to erase or cover watermark artifacts.',
    category: 'page-tools',
    path: '/remove-watermark',
    icon: 'Eraser',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    description: 'Add numbered headers or footers in customizable formats and positions.',
    category: 'page-tools',
    path: '/page-numbers',
    icon: 'Binary',
  },
  {
    id: 'header-footer',
    name: 'Header & Footer',
    description: 'Add custom titles, dates, page numbers and branding to page headers and footers.',
    category: 'page-tools',
    path: '/header-footer',
    icon: 'PanelTop',
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    description: 'Trim page margins, remove unwanted borders, or focus on specific content areas.',
    category: 'page-tools',
    path: '/crop-pdf',
    icon: 'Crop',
  },
  {
    id: 'resize-pdf',
    name: 'Resize PDF',
    description: 'Adjust page canvas dimensions to A4, Letter, A3, Legal or custom dimensions.',
    category: 'page-tools',
    path: '/resize-pdf',
    icon: 'Maximize',
  },

  // Security
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Secure your document with strong password encryption to prevent unauthorized access.',
    category: 'security',
    path: '/protect-pdf',
    icon: 'Lock',
    badge: 'Secure',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from your PDF files by providing the valid password.',
    category: 'security',
    path: '/unlock-pdf',
    icon: 'Unlock',
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently remove sensitive information, names, numbers and private content.',
    category: 'security',
    path: '/redact-pdf',
    icon: 'EyeOff',
    badge: 'Privacy',
  },
  {
    id: 'metadata',
    name: 'Edit Metadata',
    description: 'View and edit document Title, Author, Subject, Keywords and Creation information.',
    category: 'security',
    path: '/metadata',
    icon: 'FileCode',
  },

  // Other
  {
    id: 'extract-images',
    name: 'Extract Images',
    description: 'Extract every embedded raster image contained inside a PDF into separate files.',
    category: 'other',
    path: '/extract-images',
    icon: 'ImageDown',
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDF',
    description: 'Side-by-side comparison of two versions of a PDF document to spot visual differences.',
    category: 'other',
    path: '/compare-pdf',
    icon: 'Columns2',
  },
  {
    id: 'bates-numbering',
    name: 'Bates Numbering',
    description: 'Index legal, medical and business documents with formatted sequential numbering.',
    category: 'other',
    path: '/bates-numbering',
    icon: 'Hash',
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  organize: 'Organize PDF',
  edit: 'Edit & Sign',
  'convert-to': 'Convert to PDF',
  'convert-from': 'Convert from PDF',
  optimize: 'Optimize PDF',
  'page-tools': 'Page Tools',
  security: 'PDF Security',
  other: 'Other Tools',
};
