import { ToolItem, ToolCategory } from '../types';

export const TOOLS: ToolItem[] = [
  // 1. EDIT & SIGN
  {
    id: 'pdf-editor',
    name: 'PDF Editor',
    description: 'Add text, freehand drawing, highlights, shapes, images and e-signatures directly in your browser.',
    category: 'edit-sign',
    path: '/pdf-editor',
    icon: 'PenTool',
    badge: 'Flagship',
    keywords: ['edit', 'text', 'annotate', 'draw', 'highlight', 'shapes', 'signature', 'sign', 'stamp', 'private'],
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Draw, type or upload your signature and place it anywhere on document pages.',
    category: 'edit-sign',
    path: '/pdf-editor?tool=signature',
    icon: 'FileSignature',
    badge: 'Popular',
    keywords: ['sign', 'signature', 'e-sign', 'initials', 'autograph', 'contract', 'agreement'],
  },
  {
    id: 'add-text',
    name: 'Add Text',
    description: 'Type overlay text anywhere with customizable fonts, sizes, colors and alignments.',
    category: 'edit-sign',
    path: '/pdf-editor?tool=text',
    icon: 'Type',
    keywords: ['text', 'type', 'write', 'caption', 'label', 'comment'],
  },
  {
    id: 'draw-pdf',
    name: 'Draw on PDF',
    description: 'Freehand sketching, markup and highlight with adjustable stroke thickness and color.',
    category: 'edit-sign',
    path: '/pdf-editor?tool=draw',
    icon: 'Pencil',
    keywords: ['draw', 'pen', 'pencil', 'markup', 'sketch', 'scribble', 'annotate'],
  },
  {
    id: 'highlight-pdf',
    name: 'Highlight PDF',
    description: 'Mark important paragraphs and text passages with translucent color highlighters.',
    category: 'edit-sign',
    path: '/pdf-editor?tool=highlight',
    icon: 'Highlighter',
    keywords: ['highlight', 'marker', 'annotate', 'underline', 'study', 'notes'],
  },
  {
    id: 'add-shapes',
    name: 'Add Shapes',
    description: 'Insert rectangles, circles, lines and arrows with customized borders and fills.',
    category: 'edit-sign',
    path: '/pdf-editor?tool=shape',
    icon: 'Square',
    keywords: ['shape', 'rectangle', 'circle', 'arrow', 'line', 'box', 'callout'],
  },
  {
    id: 'form-filler',
    name: 'Interactive Form Field Filler',
    description: 'Click anywhere on scanned PDFs to drop fillable text fields, checkboxes, and dates.',
    category: 'edit-sign',
    path: '/tools/form-filler',
    icon: 'CheckSquare',
    badge: 'New',
    keywords: ['form', 'fill', 'checkbox', 'fields', 'application', 'survey', 'interactive'],
  },
  {
    id: 'stamp-qr-overlay',
    name: 'Stamp, Seal & QR Inserter',
    description: 'Bake official circular/rectangular rubber seals ("APPROVED", "CONFIDENTIAL") and dynamic QR codes.',
    category: 'edit-sign',
    path: '/tools/stamp-qr-overlay',
    icon: 'QrCode',
    badge: 'Official Seal',
    keywords: ['stamp', 'seal', 'qr', 'barcode', 'approved', 'confidential', 'rubber stamp'],
  },

  // 2. PAGES
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one unified document in your preferred order.',
    category: 'pages',
    path: '/merge-pdf',
    icon: 'Combine',
    badge: 'Popular',
    keywords: ['merge', 'combine', 'join', 'append', 'collate', 'unify'],
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate pages or extract specific page ranges into standalone PDFs or ZIP.',
    category: 'pages',
    path: '/split-pdf',
    icon: 'Split',
    keywords: ['split', 'separate', 'divide', 'break', 'extract pages', 'cut'],
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Sort, reorder, duplicate, delete and insert pages with visual drag & drop.',
    category: 'pages',
    path: '/organize-pdf',
    icon: 'LayoutGrid',
    badge: 'Essential',
    keywords: ['organize', 'reorder', 'sort', 'pages', 'move', 'delete page', 'duplicate'],
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    description: 'Select and permanently delete unwanted pages from your PDF file.',
    category: 'pages',
    path: '/organize-pdf?action=remove',
    icon: 'Trash2',
    keywords: ['remove', 'delete', 'trash', 'cut page', 'exclude'],
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Pull out selected pages and generate a new custom PDF document.',
    category: 'pages',
    path: '/split-pdf?mode=extract',
    icon: 'FileUp',
    keywords: ['extract', 'pull', 'select pages', 'save pages as separate'],
  },
  {
    id: 'rotate-pages',
    name: 'Rotate Pages',
    description: 'Rotate individual or all pages by 90°, 180° or 270° clockwise or counter-clockwise.',
    category: 'pages',
    path: '/rotate-pdf',
    icon: 'RotateCw',
    keywords: ['rotate', 'orientation', 'upside down', 'landscape', 'portrait', 'turn'],
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    description: 'Add numbered headers or footers in customizable formats and positions.',
    category: 'pages',
    path: '/page-numbers',
    icon: 'Binary',
    keywords: ['page numbers', 'numbering', 'pagination', 'footer numbers', 'header numbers'],
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    description: 'Trim page margins, remove unwanted borders, or focus on specific content areas.',
    category: 'pages',
    path: '/crop-pdf',
    icon: 'Crop',
    keywords: ['crop', 'trim', 'margins', 'cut borders', 'bleed'],
  },
  {
    id: 'resize-pdf',
    name: 'Resize PDF',
    description: 'Adjust page canvas dimensions to A4, Letter, A3, Legal or custom dimensions.',
    category: 'pages',
    path: '/resize-pdf',
    icon: 'Maximize',
    keywords: ['resize', 'page size', 'a4', 'letter', 'legal', 'scale page'],
  },
  {
    id: 'merge-numbering',
    name: 'Batch Merge with Continuous Numbering',
    description: 'Merge multiple PDFs in custom order and stamp continuous running page numbers.',
    category: 'pages',
    path: '/tools/merge-numbering',
    icon: 'Hash',
    badge: 'Continuous Paging',
    keywords: ['merge numbering', 'bates', 'running numbers', 'exhibits', 'legal index'],
  },
  {
    id: 'bookmark-generator',
    name: 'Bookmark & TOC Generator',
    description: 'Auto-scan headings and inject clickable table of contents bookmarks into PDF outlines.',
    category: 'pages',
    path: '/tools/bookmark-generator',
    icon: 'Bookmark',
    badge: 'TOC Outlines',
    keywords: ['bookmark', 'toc', 'table of contents', 'outlines', 'index', 'navigation'],
  },

  // 3. CONVERT
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert JPG, PNG, WEBP images into a clean, beautifully formatted PDF.',
    category: 'convert',
    path: '/image-to-pdf',
    icon: 'Image',
    badge: 'Popular',
    keywords: ['image to pdf', 'jpg to pdf', 'png to pdf', 'photos to pdf', 'pictures'],
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    description: 'Export each PDF page as high-resolution JPG or PNG packaged in a ZIP archive.',
    category: 'convert',
    path: '/pdf-to-images',
    icon: 'Images',
    badge: 'Popular',
    keywords: ['pdf to images', 'pdf to jpg', 'pdf to png', 'extract pages as photos'],
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Microsoft Word (.docx) documents into standard PDF files.',
    category: 'convert',
    path: '/word-to-pdf',
    icon: 'FileText',
    keywords: ['word to pdf', 'doc to pdf', 'docx to pdf', 'convert docx'],
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Extract text, formatting and structure into an editable Microsoft Word (.docx).',
    category: 'convert',
    path: '/pdf-to-word',
    icon: 'FileDown',
    badge: 'Popular',
    keywords: ['pdf to word', 'pdf to docx', 'convert pdf to editable word', 'docx'],
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets (.xlsx, .xls, .csv) into clean, vector-rendered PDF documents.',
    category: 'convert',
    path: '/excel-to-pdf',
    icon: 'FileSpreadsheet',
    badge: 'New',
    keywords: ['excel to pdf', 'xlsx to pdf', 'csv to pdf', 'spreadsheet to pdf'],
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract tables, spreadsheets and tabular data from PDF into editable Excel (.xlsx).',
    category: 'convert',
    path: '/pdf-to-excel',
    icon: 'Table',
    badge: 'New',
    keywords: ['pdf to excel', 'pdf to xlsx', 'extract tables', 'spreadsheet', 'csv'],
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert web code, articles and HTML snippets into clean paginated PDFs.',
    category: 'convert',
    path: '/html-to-pdf',
    icon: 'Code',
    keywords: ['html to pdf', 'webpage to pdf', 'code to pdf', 'url to pdf'],
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Extract all readable text from your PDF to copy or download as TXT / Markdown.',
    category: 'convert',
    path: '/pdf-to-text',
    icon: 'AlignLeft',
    keywords: ['pdf to text', 'extract text', 'copy text', 'txt', 'markdown'],
  },
  {
    id: 'scan-to-pdf',
    name: 'Document Camera Scanner',
    description: 'Scan physical papers, notes & receipts with live camera, rear lens priority & auto-perspective crop.',
    category: 'convert',
    path: '/scan-to-pdf',
    icon: 'Camera',
    badge: 'New',
    keywords: ['camera scanner', 'scan to pdf', 'phone scanner', 'camscanner', 'photo scan'],
  },

  // 4. COMPRESS & OPTIMIZE
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size while preserving document visual clarity and image sharpness.',
    category: 'compress',
    path: '/compress-pdf',
    icon: 'Minimize2',
    badge: 'Popular',
    keywords: ['compress', 'shrink', 'reduce size', 'optimize', 'under 200kb', 'small pdf'],
  },
  {
    id: 'ink-saver',
    name: 'Ink Saver & Toner Eco Mode',
    description: 'Strip dark background fills and colored slide backgrounds to save up to 70% printer ink.',
    category: 'compress',
    path: '/tools/ink-saver',
    icon: 'Droplet',
    badge: 'Save ~70% Ink',
    keywords: ['ink saver', 'grayscale', 'black and white', 'save toner', 'eco print'],
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Fix corrupt, damaged or unreadable PDF files and rebuild document xref tables.',
    category: 'compress',
    path: '/repair-pdf',
    icon: 'Wrench',
    keywords: ['repair', 'fix', 'corrupt pdf', 'recover', 'damaged pdf', 'restore'],
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    description: 'Merge form fields, layers and annotations into one permanent uneditable surface.',
    category: 'compress',
    path: '/flatten-pdf',
    icon: 'Layers',
    keywords: ['flatten', 'bake annotations', 'lock fields', 'uneditable', 'print ready'],
  },
  {
    id: 'booklet-formatter',
    name: 'Booklet Print Formatter',
    description: 'Impose 2-up or 4-up pages onto single A4/Letter sheets with folding cut-lines.',
    category: 'compress',
    path: '/tools/booklet-formatter',
    icon: 'BookOpen',
    badge: 'Paper Saver',
    keywords: ['booklet', '2-up', '4-up', 'fold', 'pamphlet', 'save paper'],
  },
  {
    id: 'n-up-imposition',
    name: 'Multi-Page N-Up Imposition',
    description: 'Impose 2-up, 4-up, and 9-up pages onto single A4/A3/Letter sheets with cutting guidelines.',
    category: 'compress',
    path: '/tools/n-up-imposition',
    icon: 'LayoutGrid',
    badge: 'Print Shop Pro',
    keywords: ['n-up', 'imposition', 'print shop', 'multi-page per sheet', 'grid'],
  },

  // 5. SECURE & PROTECT
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Secure your document with strong password encryption to prevent unauthorized access.',
    category: 'secure',
    path: '/protect-pdf',
    icon: 'Lock',
    badge: 'Secure',
    keywords: ['protect', 'password', 'encrypt', 'security', 'lock pdf', 'confidential'],
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from your PDF files by providing the valid password.',
    category: 'secure',
    path: '/unlock-pdf',
    icon: 'Unlock',
    keywords: ['unlock', 'remove password', 'decrypt', 'open locked pdf'],
  },
  {
    id: 'unlock-permissions',
    name: 'PDF Permission Unlocker',
    description: 'Strip printing locks, copy protection, and editing restrictions to create clean unrestricted PDFs.',
    category: 'secure',
    path: '/tools/unlock-permissions',
    icon: 'Unlock',
    badge: 'Unrestricted',
    keywords: ['strip restrictions', 'enable print', 'allow copy', 'permissions unlock'],
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently remove sensitive information, names, numbers and private content.',
    category: 'secure',
    path: '/redact-pdf',
    icon: 'EyeOff',
    badge: 'Privacy',
    keywords: ['redact', 'blackout', 'hide confidential', 'censor', 'remove private data'],
  },
  {
    id: 'metadata',
    name: 'Edit Metadata',
    description: 'View and edit document Title, Author, Subject, Keywords and Creation information.',
    category: 'secure',
    path: '/metadata',
    icon: 'FileCode',
    keywords: ['metadata', 'author', 'title', 'subject', 'properties', 'tags'],
  },
  {
    id: 'batch-renamer',
    name: 'Batch Renamer & Metadata Wiper',
    description: 'Bulk rename 50+ PDFs with prefix, suffix, date, sequential [001] numbering, and strip metadata.',
    category: 'secure',
    path: '/tools/batch-renamer',
    icon: 'FolderArchive',
    badge: 'Bulk 50+ Files',
    keywords: ['batch rename', 'bulk files', 'clean metadata', 'rename pattern', 'prefix'],
  },

  // 6. MORE TOOLS
  {
    id: 'ocr-pdf',
    name: 'OCR Scanner',
    description: 'Scan image-based or photographed PDFs with optical character recognition into selectable text & Word.',
    category: 'more-tools',
    path: '/ocr-pdf',
    icon: 'ScanText',
    badge: 'AI Powered',
    keywords: ['ocr', 'text recognition', 'scanned pdf', 'searchable pdf', 'image text'],
  },
  {
    id: 'vernacular-ocr',
    name: 'Hindi & English OCR to Word',
    description: 'Extract Hindi Devanagari and English text from scanned PDFs/photos with rich-text editor and DOCX export.',
    category: 'more-tools',
    path: '/tools/vernacular-ocr',
    icon: 'Languages',
    badge: 'Hindi & Eng OCR',
    keywords: ['hindi ocr', 'devanagari ocr', 'vernacular', 'bilingual', 'hindi to docx'],
  },
  {
    id: 'add-watermark',
    name: 'Watermark PDF',
    description: 'Stamp custom text or image watermarks across pages with opacity and angle controls.',
    category: 'more-tools',
    path: '/add-watermark',
    icon: 'Stamp',
    badge: 'Featured',
    keywords: ['watermark', 'stamp text', 'draft', 'confidential', 'branding', 'logo'],
  },
  {
    id: 'remove-watermark',
    name: 'Remove Watermark',
    description: 'Visual cleanup and redaction workflow to erase or cover watermark artifacts.',
    category: 'more-tools',
    path: '/remove-watermark',
    icon: 'Eraser',
    keywords: ['remove watermark', 'erase watermark', 'clean pdf'],
  },
  {
    id: 'header-footer',
    name: 'Header & Footer',
    description: 'Add custom titles, dates, page numbers and branding to page headers and footers.',
    category: 'more-tools',
    path: '/header-footer',
    icon: 'PanelTop',
    keywords: ['header', 'footer', 'title top', 'date bottom', 'running header'],
  },
  {
    id: 'compare-pdf',
    name: 'Side-by-Side PDF Diff',
    description: 'Compare two versions of a document with side-by-side pages, word/line text clause diff, and heatmap.',
    category: 'more-tools',
    path: '/compare-pdf',
    icon: 'Columns2',
    badge: 'Diff & Clauses',
    keywords: ['compare', 'diff', 'side by side', 'clause check', 'version diff'],
  },
  {
    id: 'bates-numbering',
    name: 'Bates Numbering',
    description: 'Index legal, medical and business documents with formatted sequential numbering.',
    category: 'more-tools',
    path: '/bates-numbering',
    icon: 'Hash',
    keywords: ['bates', 'legal numbering', 'discovery', 'case file', 'sequential'],
  },
  {
    id: 'listen-pdf',
    name: 'Audio PDF Reader',
    description: 'Listen to PDF documents with Hindi & English text-to-speech voice controls and speed tuning.',
    category: 'more-tools',
    path: '/tools/listen-pdf',
    icon: 'Headphones',
    badge: 'Voice AI',
    keywords: ['listen', 'tts', 'text to speech', 'audio reader', 'read aloud', 'voice'],
  },
  {
    id: 'extract-images',
    name: 'Extract Images',
    description: 'Extract every embedded raster image contained inside a PDF into separate files.',
    category: 'more-tools',
    path: '/extract-images',
    icon: 'ImageDown',
    keywords: ['extract images', 'rip images', 'save embedded pictures', 'download photos'],
  },
  {
    id: 'carousel-maker',
    name: 'Social Media Carousel Maker',
    description: 'Convert PDF slides and notes into 1080x1350 vertical or square Instagram/LinkedIn carousel images.',
    category: 'more-tools',
    path: '/tools/carousel-maker',
    icon: 'Share2',
    badge: 'Social Media',
    keywords: ['carousel', 'instagram', 'linkedin', 'slides to images', 'post maker'],
  },

  // 7. SPECIALIZED WORKFLOW HUBS
  {
    id: 'wedding-studio',
    name: 'Wedding Studio Hub',
    description: 'All-in-one suite for event photographers: Client Proofing, Quotation & Contract Maker, and Guest Badges.',
    category: 'hubs',
    path: '/wedding-studio',
    icon: 'Sparkles',
    badge: 'Studio Hub',
    isNicheHub: true,
    keywords: ['wedding', 'photographer', 'studio', 'event', 'album selection'],
  },
  {
    id: 'photo-proofing',
    name: 'Photo Proofing & Selection',
    description: 'Interactive client photo selection for wedding & event albums with 5-star ratings and sorted PDF export.',
    category: 'hubs',
    path: '/wedding-studio/proofing',
    icon: 'Star',
    badge: 'Wedding & Event Pro',
    isNicheHub: true,
    keywords: ['proofing', 'client selection', 'photo rating', 'wedding album', 'reject photos'],
  },
  {
    id: 'wedding-quotation',
    name: 'Wedding Quotation & Contract',
    description: 'Create professional photography quotations, packages, auto-tax totals, and integrated dual e-signatures.',
    category: 'hubs',
    path: '/wedding-studio/quotation',
    icon: 'Calculator',
    badge: 'New',
    isNicheHub: true,
    keywords: ['quotation', 'invoice', 'photography contract', 'package pricing', 'e-sign agreement'],
  },
  {
    id: 'guest-cards',
    name: 'Guest Badges & Tent Cards',
    description: 'Generate elegant printable table tent cards and VIP guest badges with cut-lines from names/CSV.',
    category: 'hubs',
    path: '/wedding-studio/guest-cards',
    icon: 'Tag',
    badge: 'Print Ready',
    isNicheHub: true,
    keywords: ['guest badges', 'tent cards', 'table cards', 'name cards', 'csv import'],
  },
  {
    id: 'id-card-layout',
    name: 'ID Card Print Layout',
    description: 'Arrange Aadhaar, PAN, and Voter ID front & back in 4-in-1 and 8-in-1 print-ready A4 layouts with scissor marks.',
    category: 'hubs',
    path: '/tools/id-card-layout',
    icon: 'CreditCard',
    badge: 'Cyber Cafe Pro',
    isNicheHub: true,
    keywords: ['id card', 'aadhaar', 'pan card', 'voter id', 'cyber cafe', '4 in 1', 'scissor marks'],
  },
  {
    id: 'govt-form-resizer',
    name: 'Govt Exam Photo & Sig Resizer',
    description: 'Exact pixel dimension and target KB compressor for SSC, UPSC, IBPS, NTA recruitment application forms.',
    category: 'hubs',
    path: '/tools/govt-form-resizer',
    icon: 'Camera',
    badge: 'Govt Exam Pro',
    isNicheHub: true,
    keywords: ['govt exam', 'ssc', 'upsc', 'photo resizer', 'signature under 20kb', 'nta'],
  },
  {
    id: 'perspective-cropper',
    name: 'Perspective Auto-Crop & Flattener',
    description: '4-point draggable quad selector to rectify and flatten tilted phone camera document photos into scanner sheets.',
    category: 'hubs',
    path: '/tools/perspective-cropper',
    icon: 'Crop',
    badge: 'Photo Flattener',
    isNicheHub: true,
    keywords: ['perspective', 'quad crop', 'keystone fix', 'deskew', 'flatten photo', 'skew correction'],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  'edit-sign': 'Edit & Sign',
  pages: 'Pages & Organize',
  convert: 'Convert PDF',
  compress: 'Compress & Optimize',
  secure: 'Secure & Protect',
  'more-tools': 'More Tools',
  hubs: 'Specialized Studio Hubs',

  // Backwards compatibility aliases
  organize: 'Pages & Organize',
  edit: 'Edit & Sign',
  'convert-to': 'Convert to PDF',
  'convert-from': 'Convert from PDF',
  optimize: 'Compress & Optimize',
  'page-tools': 'Page Tools',
  security: 'Secure & Protect',
  other: 'More Tools',
};
